### ISSUE TITLE
Forced SSLv3

### ISSUE THREAD

**Issue by magnusnordlander** [BeSimple/BeSimpleSsoAuthBundle#80]
Hi,

This bundle forces the SSLv3 option on cURL. With the POODLE attack, more and more servers are disabling SSLv3, which means this will start generating connection errors.

What's the reasoning behind forcing SSLv3? If we're forcing protocols, shouldn't we be forcing TLSv1 (constant 1)?

**Comment by mcrauwel** [comment]
Why not default to value 0 (being the system default)?

**Comment by cilefen** [comment]
@bkosborne I added that to a [reference implementation](https://github.com/theias/symfony-cas).

It should be [set to 0](http://php.net/manual/en/function.curl-setopt.php).

`parameters:
    be_simple.sso_auth.client.option.curlopt_sslversion.value: 0`
