### ISSUE TITLE
Allow definition for curl timeout & add the possibility to use the check_url config

### ISSUE THREAD

**Issue by clement-garrigou** [BeSimple/BeSimpleSsoAuthBundle#92]
Does anyone can take a look at this pull request [#86](https://github.com/BeSimple/BeSimpleSsoAuthBundle/pull/86), to be sure that they are correct ? 
Thanks in advance

**Comment by acidjames** [comment]
Hi @clement-garrigou 

thanks for your contribution, could you be a little more specific about the check_url config ? 
In which scenario is curl timeout used ?

Thanks

**Comment by clement-garrigou** [comment]
- **check_url** allow to choose the url to redirect after the SSO authentication. You can see it in the service parameter : https://www.example-cas-server.com/cas/login?service=https://www.final_url.com

Configuration :
be_simple_sso_auth:
    admin_sso:
        server:
            id: cas
            ...
            check_url: https://www.final_url.com

- The timeout can be useful to define if the SSO take time to reach. I suggest 5 seconds by default, but you can change it easily by configuration

**Comment by acidjames** [comment]
Salut @clement-garrigou 

ok pour le timeout

par contre, y'a un truc que je ne comprend vraiment pas... dans ta propostion du Factory.php, j'ai testé et ça fonctionne comme convenu

mais je vois pas en quoi de rajouter la vérification du !isset change quelquechose

A l'origine, le code force la valeur du check_url dans tous les cas... y'a un truc que j'ai loupé ?

**Comment by acidjames** [comment]
Ok, j'ai cherché un peu en remontant ici : 

https://github.com/BeSimple/BeSimpleSsoAuthBundle/blob/master/Security/Http/EntryPoint/TrustedSsoAuthenticationEntryPoint.php#L49

`$manager = $this->factory->getManager($this->config['manager'], $request->getUriForPath($this->config['check_path']));`

A priori, ici le check_url est systématiquement écrasé par la valeur de 'check_path', check path étant une propriété de security.yml

On devrait corriger cette portion plutot pour que ça soit logique, qu'en penses tu ?

**Comment by clement-garrigou** [comment]
OK sur le principe c'est vrai que ça semble plus logique. Tu veux que je regarde ?

**Comment by acidjames** [comment]
Oui effectivement, c'est plus compliqué qu'il n'y parait car il faudrait en plus injecter la config du bundle dans l'authentication car check_url n'est pas un paramètre standard du security framework de symfony...

Par contre, une idée juste comme ça, tu as testé d'utiliser le paramètre 'check_path' comme 'check_url' dans ton contexte ? Car au final, cela reviendrait au même non ?

**Comment by clement-garrigou** [comment]
J'ai testé : check_path sert à modifier le path de l'url de retour. On ne peut pas l'utiliser pour changer complétement l'url de retour, ce qui serait possible avec check_url.

**Comment by acidjames** [comment]
J'ai mergé la PR, désolé pour le temps pris pour l'analyse ^^

Je ne sais pas si ce projet est connecté à l'API de packagist.org du coup, ça risque de prendre 24h à 48h pour disposer de la mise à jour sur composer

Merci pour ta contribution et à bientot,
James

**Comment by clement-garrigou** [comment]
Merci !
