### ISSUE TITLE
cannot dump configuration

### ISSUE THREAD

**Issue by garak** [BeSimple/BeSimpleSsoAuthBundle#94]
After installing and configuring this bundle, I tried to execute `bin/console debug:config be_simple_sso_auth` and got the following error:

```
[LogicException]                                                                                 
The extension with alias "be_simple_sso_auth" does not have its getConfiguration() method setup
```

**Comment by acidjames** [comment]
Hi @garak 

i don't have any debug command called "configuration", neither in sf2, nor sf3, what's that ?

**Comment by garak** [comment]
My bad, the command is `debug:config`, not `debug:configuration` (I edited my original message)

**Comment by acidjames** [comment]
haha i guess i'm blind because i could've guessed that...

well apparently, the command now works, i can't reproduce the bug so i'll close this
