### ISSUE TITLE
Not Working since I upgraded my workstation on Ubuntu 16.04

### ISSUE THREAD

**Issue by berduj** [BeSimple/BeSimpleSsoAuthBundle#95]
This bundle use to work fine on my laptop Ubuntu 14.04.
Since I upgraded my workstation to Ubuntu 16.04 it doesn't work and a message is displayed : 
"SSL: couldn't create a context: error:140A90C4:SSL routines:SSL_CTX_new:null ssl method passed"

The problem is the version of SSL that is disabled on Ubuntu 16.04.
To avoid it, I added this line in parameters.yml to force TLS instead of SSL:
    be_simple.sso_auth.client.option.curlopt_sslversion.value: 1

**Comment by acidjames** [comment]
Thanks for contributing
